config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "admin/categories#index"

  scope 'admin', module: 'admin', :as => "admin" do
    resources :categories
    resources :dishes
    resources :orders, only: :index do
      member do
        get :dishes_list
      end
    end
    resources :reports, only: :index
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :dishes
      resources :orders, only: :create
      post   "/sign-in"       => "sessions#create"
      delete "/sign-out"      => "sessions#destroy"
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishes
  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :children, class_name: "Category", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Category", foreign_key: "parent_id"

  scope :roots, -> { where(parent_id: nil) }

  def full_name
    return name if parent.blank?
    parent.full_name + "/#{name}"
  end
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :category
  has_many :dishes_orders
  has_and_belongs_to_many :orders

  validates_presence_of :name, :category_id, :price

  class << self
    def by_params(params)
      dishes = Dish.includes(:category)
      dishes = dishes.where(category: params[:category_id]) unless params[:category_id].blank?
      dishes.order("categories.name")
    end
  end

  def category_name
    category.name || ""
  end
end

app/models/dishes_order.rb
class DishesOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :dish
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :dishes_orders
  has_and_belongs_to_many :dishes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #:recoverable, :trackable,
  has_many :orders

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates_presence_of :login
  validates_uniqueness_of :login

  before_save :ensure_authentication_token

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def invalidate_auth_token
    self.update_columns(authentication_token: generate_authentication_token)
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_categories, only: [:index, :create, :update, :destroy]

  def index
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(category_params)
      render :refresh_categories
    else
      render :action => 'edit'
    end
  end

  def create
    @category = Category.new category_params

    if @category.save
      render :refresh_categories
    else
      render action: :new
    end
  end

  def new
    @category = Category.new
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    render :refresh_categories
  end

  private
    def set_categories
      @categories = Category.order("created_at DESC").page(params[:page])
    end

    def category_params
      params.require(:category).permit(:name,:parent_id)
    end
end

app/controllers/admin/dishes_controller.rb
class Admin::DishesController < Admin::BaseController
  before_action :set_dishes, only: [:index, :create, :update, :destroy]

  def index
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])

    if @dish.update_attributes(dish_params)
      render :refresh_dishes
    else
      render :action => 'edit'
    end
  end

  def create
    @dish = Dish.new dish_params

    if @dish.save
      render :refresh_dishes
    else
      render action: :new
    end
  end

  def new
    @dish = Dish.new
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    render :refresh_dishes
  end

  private
    def set_dishes
      @dishes = Dish.includes(:category).order("categories.name").page(params[:page])
    end

    def dish_params
      params.require(:dish).permit(:name, :category_id, :price)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.order("created_at DESC").page(params[:page])
  end

  def dishes_list
    order = Order.find_by(id: params[:id])
    @dishes = order.dishes
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController

  def index
    #TODO: cache orders count
    @dishes = Dish.joins(:orders).group("dishes.id").order("count(orders.id) DESC").page(params[:page])
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!

  def authenticate_user_from_token!
    user_token = params[:user_token].presence
    user       = user_token && User.find_by_authentication_token(user_token.to_s)

    if user
      sign_in user, store: false
    end
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < Api::BaseController
  skip_before_action :authenticate_user!, only: [:create]

  #curl -X POST --data "user[login]=admin&user[password]=123456" http://localhost:3000/api/v1/sign-in
  def create
    resource = User.find_for_database_authentication(:login => params[:user][:login])
    return invalid_login unless resource

    if resource.valid_password?(params[:user][:password])
      auth_token = resource.authentication_token
      render json: { auth_token: auth_token }
    else
      invalid_login
    end

  end

  #curl -X DELETE --data "user_token=#{token}" http://localhost:3000/api/v1/sign-out
  def destroy
    resource = current_user
    resource.invalidate_auth_token
    head :ok
  end

  private
    def invalid_login
      render json: { errors: [ { detail: "Invalid login or password" }]}, status: 401
    end
end

app/controllers/api/v1/dishes_controller.rb
module Api
  module V1
    class DishesController < Api::BaseController
      respond_to :json

      # GET /api/v1/dishes
      # params:
      #   ?category_id=1
      def index
        render json: ::Dishes::GetListService.build(params)
      end

    end
  end
end

app/controllers/api/v1/orders_controller.rb
module Api
  module V1
    class OrdersController < Api::BaseController
      respond_to :json

      #curl -X POST --data "order[dish_ids][]=1&order[dish_ids]=2" http://localhost:3000/api/v1/orders?user_token=#{token}
      def create
        order = Order.new order_params
        order.user_id = current_user.id

        respond_to do |format|
          if order.save
            format.json {render json: {status: "ok"}}
          else
            format.json {render json: {status: 401}}
          end
        end
      end

      private
        def order_params
          params.require(:order).permit(:dish_ids => [])
        end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:login, :email, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :email, :password, :password_confirmation, :remember_me])
  end

  def after_sign_in_path_for(resource)
    admin_categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_options(object)
    Category.where.not(id: object.id)
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= l(category.created_at, :format => :long )%></td>
  <th><%= category.full_name %></th>
  <td>
    <%= link_to edit_admin_category_path(category), remote: true do %><i class="glyphicon glyphicon-pencil"></i><% end %>
    <%= link_to admin_category_path(category), remote: true, data: {:confirm => 'Вы уверены?'}, :method => :delete do %><i class="glyphicon glyphicon-remove"></i><%end%>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for [:admin, @category], remote: true, html: {class: 'form-horizontal', role: 'form'} do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"> &times;</span>
        </button>
        <h4 class="modal-title">Управление категорией</h4>
      </div>

      <div class="modal-body">
        <div class="form-inputs">
          <%= f.input :name, label: "Наименование:" %>
          <%= f.association :parent, label: "Родительская категория", collection: category_options(f.object) %>
        </div>
      </div>

      <div class="modal-footer">
        <div class="form-actions">
          <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/categories/edit.js.erb
$("#modal-form").html("<%= escape_javascript(render('form')) %>");
$("#modal-form").modal("show");

app/views/admin/categories/index.html.erb
<div class="create-new-record">
  <%= link_to new_admin_category_path, class: "btn btn-primary pull-right", remote: true do %>
    Создать Категорию
    <i class="glyphicon glyphicon-plus"></i>
  <% end %>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Наименование</th>
      <th>Дата создания</th>
      <th>Полное наименование</th>
      <th>Действия</th>
    </tr>
    <tbody id="categories-body">
      <%= render @categories %>
    </tbody>
  </thead>
</table>

<%= paginate @categories %>

<%= render partial: "partials/modal_form" %>

app/views/admin/categories/index.js.erb
$("#modal-form").modal("hide");
$('#categories-body').fadeOut('slow', function() {
  $('#categories-body').html("<%= j (render @categories) %>");
  $('#categories-body').fadeIn('slow');
});

app/views/admin/categories/new.js.erb
$("#modal-form").html("<%= escape_javascript(render('form')) %>");
$("#modal-form").modal("show");

app/views/admin/categories/refresh_categories.js.erb
$("#modal-form").modal("hide");
$('#categories-body').fadeOut('slow', function() {
  $('#categories-body').html("<%= j (render @categories) %>");
  $('#categories-body').fadeIn('slow');
});

app/views/admin/dishes/_dish.html.erb
<tr>
  <td><%= dish.name %></td>
  <td><%= dish.category.name if dish.category %></td>
  <td><%= dish.price %></td>
  <td>
    <%= link_to edit_admin_dish_path(dish), remote: true do %><i class="glyphicon glyphicon-pencil"></i><% end %>
    <%= link_to admin_dish_path(dish), remote: true, data: {:confirm => 'Вы уверены?'}, :method => :delete do %><i class="glyphicon glyphicon-remove"></i><%end%>
  </td>
</tr>

app/views/admin/dishes/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for [:admin, @dish], remote: true, html: {class: 'form-horizontal', role: 'form'} do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"> &times;</span>
        </button>
        <h4 class="modal-title">Управление блюдом</h4>
      </div>

      <div class="modal-body">
        <div class="form-inputs">
          <%= f.input :name, label: "Наименование:"  %>
          <%= f.input :price, label: "Стоимость:"  %>
          <%= f.association :category, label: "Категория:"  %>
        </div>
      </div>

      <div class="modal-footer">
        <div class="form-actions">
          <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/dishes/edit.js.erb
$("#modal-form").html("<%= escape_javascript(render('form')) %>");
$("#modal-form").modal("show");

app/views/admin/dishes/index.html.erb
<div class="create-new-record">
  <%= link_to new_admin_dish_path, class: "btn btn-primary pull-right", remote: true do %>
    Создать блюдо
    <i class="glyphicon glyphicon-plus"></i>
  <% end %>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th><%= t("index.title")%></th>
      <th>Категория</th>
      <th>Стоимость</th>
      <th><%= t("index.actions")%></th>
    </tr>
    <tbody id="dishes-body">
      <%= render @dishes %>
    </tbody>
  </thead>
</table>

<%= paginate @dishes %>

<%= render partial: "partials/modal_form" %>

app/views/admin/dishes/index.js.erb
$("#modal-form").modal("hide");
$('#categories-body').fadeOut('slow', function() {
  $('#categories-body').html("<%= j (render @categories) %>");
  $('#categories-body').fadeIn('slow');
});

app/views/admin/dishes/new.js.erb
$("#modal-form").html("<%= escape_javascript(render('form')) %>");
$("#modal-form").modal("show");

app/views/admin/dishes/refresh_dishes.js.erb
$("#modal-form").modal("hide");
$('#dishes-body').fadeOut('slow', function() {
  $('#dishes-body').html("<%= j (render @dishes) %>");
  $('#dishes-body').fadeIn('slow');
});

app/views/admin/orders/_dishes_list.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"> &times;</span>
      </button>
      <h4 class="modal-title">Список блюд</h4>
    </div>

    <div class="modal-body">
      <ul>
        <% @dishes.each do |dish| %>
          <li><%= "#{dish.name} (#{dish.price})" %></li>
        <% end %>
      </ul>
    </div>

    <div class="modal-footer">
      <button class="btn.btn-primary" aria-hidden="true" data-dismiss="modal">Закрыть</button>
    </div>
  </div>
</div>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= order.user.login if order.user %></td>
  <td><%= link_to order.dishes.count, dishes_list_admin_order_path(order), remote: true %></td>
  <th><%= order.dishes.pluck(:price).sum %></th>
  <td><%= l(order.created_at, :format => :long )%></td>
</tr>

app/views/admin/orders/dishes_list.js.erb
$("#modal-form").html("<%= escape_javascript(render('dishes_list')) %>");
$("#modal-form").modal("show");

app/views/admin/orders/index.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Пользователь</th>
      <th>Кол-во товаров</th>
      <th>Стоимость</th>
      <th>Дата создания</th>
    </tr>
    <tbody id="orders-body">
      <%= render @orders %>
    </tbody>
  </thead>
</table>

<%= paginate @orders %>

<%= render partial: "partials/modal_form" %>

app/views/admin/reports/index.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Наименование</th>
      <th>Категория</th>
      <th>Кол-во продаж</th>
      <th>Выручка</th>
    </tr>
    <tbody id="report-body">
      <% @dishes.each do |dish| %>
        <tr>
          <td><%= dish.name %></td>
          <td><%= dish.category_name %></td>
          <td><%= sold_count = dish.orders.count %></td>
          <td><%= dish.price*sold_count %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>
</table>

<%= paginate @dishes %>

app/views/layouts/_flash_messages.html.erb
<% unless flash[:alert].blank? %>
  <div class="alert alert-danger">
    <h4><%= flash[:alert] %></h4>
  </div>
<% end %>

<% unless flash[:notice].blank? %>
  <div class="alert alert-success">
    <h4><%= flash[:notice] %></h4>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="glyphicon glyphicon-bar"></span>
      <span class="glyphicon glyphicon-bar"></span>
      <span class="glyphicon glyphicon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
    <p class="navbar-text navbar-right">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, :method => :delete do %>
          <i class="glyphicon glyphicon-user"></i> Выйти
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="glyphicon glyphicon-user"></i> Войти
        <% end %>
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GladsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render :partial => "layouts/navbar" %>
    <%= render :partial => "layouts/flash_messages" %>
    <div class="row">
      <div class="col-md-3 col-lg-3">
        <div class="well sidebar-nav">
          <ul id="main-left-bar" class="nav nav-list">
            <li class="nav-header">Основной раздел</li>
            <li><%= link_to t('menu.categories'), admin_categories_path %></li>
            <li><%= link_to t('menu.dishes'), admin_dishes_path %></li>
            <li><%= link_to t('menu.orders'), admin_orders_path %></li>
            <li><%= link_to t('menu.reports'), admin_reports_path %></li>
        </ul>
        </div><!--/.well -->
      </div>

      <div class="col-md-9 col-lg-9">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GladsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:body_class) %>">
  <div class="container">
    <%= render :partial => "layouts/flash_messages" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/partials/_modal_form.html.erb
<div id="modal-form" class="modal fade" aria-hidden="false">
</div>